name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: npm run type-check
      - run: npm run test
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ab7786153e7183e5db0f5cfdec8b19bce91e78dcc4c482461f94a43b1e09c89b
        with:
          coverageLocations: |
            ${{github.workspace}}/coverage/jest/lcov.info:lcov
          debug: true
#      - name: Release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#        run: npx semantic-release
